### PR TITLE
Convert to C and add mouse button support 

### PR DESCRIPTION
**Pull request by effective-light**

### CODE REVIEW

**Comment by Rush** [comment]
Thank you for the pull request. May I ask what benefit does ANSI C bring over C++? 

C++ can do everything that C can but can potentially allow easier access to advanced data structures and memory safe patterns (shared_ptr). I know this project didn't yet use such bells and whistles but I'd like to keep our options open.

**Comment by Rush** [comment]
Otherwise I like your mouse support feature. Would prefer to rebase it on top of C++

**Comment by effective-light** [comment]
C just seemed like a better fit for this project, considering the fact that most of the X11 and compositor landscape is written exclusively in C. But, if you prefer to stick to C++ that's fine.

**Comment by Rush** [comment]
@effective-light I used both C and C++ extensively in my career. I think if someone ever adds support for a config file or some other features that could be considered more advanced, I think C++ will make it extremely easy to implement. I would hate to see somebody implementing a hash table in C for example. :-P

**Pull request closed without merging**
